import type { Product, Category, User, Review, Seller } from './types';

// Mock Sellers
export const mockSellers: Seller[] = [
  {
    id: 'seller1',
    name: 'TechGear Pro',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop',
    rating: 4.8,
    reviewCount: 12450,
    description: 'Premium technology accessories and gadgets',
    joinedDate: new Date('2020-01-15'),
  },
  {
    id: 'seller2',
    name: 'HomeStyle Living',
    logo: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=100&h=100&fit=crop',
    rating: 4.6,
    reviewCount: 8930,
    description: 'Quality home and lifestyle products',
    joinedDate: new Date('2019-08-20'),
  },
  {
    id: 'seller3',
    name: 'SportMax',
    logo: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100&h=100&fit=crop',
    rating: 4.7,
    reviewCount: 15670,
    description: 'Athletic gear and fitness equipment',
    joinedDate: new Date('2018-03-10'),
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=200&h=200&fit=crop',
    productCount: 15420,
    subcategories: [
      { id: 'smartphones', name: 'Smartphones', slug: 'smartphones', productCount: 2340 },
      { id: 'laptops', name: 'Laptops', slug: 'laptops', productCount: 1890 },
      { id: 'headphones', name: 'Headphones', slug: 'headphones', productCount: 3450 },
    ],
  },
  {
    id: 'home-garden',
    name: 'Home & Garden',
    slug: 'home-garden',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200&h=200&fit=crop',
    productCount: 8920,
    subcategories: [
      { id: 'furniture', name: 'Furniture', slug: 'furniture', productCount: 2100 },
      { id: 'decor', name: 'Home Decor', slug: 'decor', productCount: 3200 },
      { id: 'kitchen', name: 'Kitchen', slug: 'kitchen', productCount: 1890 },
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Outdoors',
    slug: 'sports',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop',
    productCount: 6540,
    subcategories: [
      { id: 'fitness', name: 'Fitness', slug: 'fitness', productCount: 1200 },
      { id: 'outdoor', name: 'Outdoor Recreation', slug: 'outdoor', productCount: 890 },
      { id: 'team-sports', name: 'Team Sports', slug: 'team-sports', productCount: 1100 },
    ],
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review1',
    userId: 'user1',
    userName: 'John D.',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop',
    productId: 'prod1',
    rating: 5,
    title: 'Excellent quality and fast shipping!',
    content: 'This product exceeded my expectations. The build quality is outstanding and it arrived exactly as described. Highly recommend!',
    verified: true,
    helpful: 23,
    notHelpful: 1,
    createdAt: new Date('2024-05-15'),
  },
  {
    id: 'review2',
    userId: 'user2',
    userName: 'Sarah M.',
    userAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b442?w=40&h=40&fit=crop',
    productId: 'prod1',
    rating: 4,
    title: 'Good value for money',
    content: 'Works as expected, good quality materials. Only minor issue is the packaging could be better.',
    verified: true,
    helpful: 15,
    notHelpful: 2,
    createdAt: new Date('2024-05-10'),
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'prod1',
    title: 'Wireless Bluetooth Headphones - Premium Sound Quality',
    description: 'Experience crystal-clear audio with our premium wireless headphones featuring active noise cancellation, 30-hour battery life, and premium comfort design.',
    price: 199.99,
    originalPrice: 299.99,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&h=500&fit=crop',
    ],
    category: 'electronics',
    subcategory: 'headphones',
    brand: 'AudioTech',
    seller: mockSellers[0],
    specifications: {
      'Driver Size': '40mm',
      'Frequency Response': '20Hz - 20kHz',
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '250g',
    },
    features: [
      'Active Noise Cancellation',
      'Quick Charge (5 min = 2 hours)',
      'Voice Assistant Compatible',
      'Foldable Design',
      'Premium Leather Ear Cups',
    ],
    inStock: true,
    stockQuantity: 45,
    rating: 4.6,
    reviewCount: 234,
    reviews: mockReviews,
    variants: [
      {
        id: 'color',
        name: 'Color',
        options: [
          { value: 'Black', inStock: true },
          { value: 'White', inStock: true },
          { value: 'Blue', inStock: false },
        ],
      },
    ],
    tags: ['wireless', 'bluetooth', 'noise-cancelling', 'premium'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'prod2',
    title: 'Smart Home Security Camera - 4K Ultra HD',
    description: 'Keep your home secure with our advanced 4K security camera featuring night vision, motion detection, and smartphone integration.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1580911390019-2dd8713b7c02?w=500&h=500&fit=crop',
    ],
    category: 'electronics',
    subcategory: 'smart-home',
    brand: 'SecureHome',
    seller: mockSellers[0],
    specifications: {
      'Resolution': '4K Ultra HD',
      'Field of View': '130°',
      'Night Vision': 'Up to 30ft',
      'Storage': 'Cloud & Local',
      'Connectivity': 'WiFi 6',
    },
    features: [
      '4K Ultra HD Recording',
      'Color Night Vision',
      'Two-Way Audio',
      'Motion Detection',
      'Weather Resistant',
    ],
    inStock: true,
    stockQuantity: 32,
    rating: 4.8,
    reviewCount: 189,
    reviews: [],
    tags: ['security', 'smart-home', '4k', 'wifi'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-05-18'),
  },
  {
    id: 'prod3',
    title: 'Ergonomic Office Chair - Professional Series',
    description: 'Transform your workspace with our premium ergonomic office chair designed for all-day comfort and productivity.',
    price: 299.99,
    originalPrice: 399.99,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1549497538-303791108f95?w=500&h=500&fit=crop',
    ],
    category: 'home-garden',
    subcategory: 'furniture',
    brand: 'ComfortPro',
    seller: mockSellers[1],
    specifications: {
      'Material': 'Premium Mesh & Fabric',
      'Weight Capacity': '300 lbs',
      'Height Range': '17"-21"',
      'Warranty': '5 years',
      'Assembly': 'Easy 30-min setup',
    },
    features: [
      'Lumbar Support',
      'Adjustable Armrests',
      'Breathable Mesh Back',
      'Smooth Rolling Casters',
      '360° Swivel',
    ],
    inStock: true,
    stockQuantity: 18,
    rating: 4.7,
    reviewCount: 156,
    reviews: [],
    variants: [
      {
        id: 'color',
        name: 'Color',
        options: [
          { value: 'Black', inStock: true },
          { value: 'Gray', inStock: true },
          { value: 'Navy', inStock: false },
        ],
      },
    ],
    tags: ['office', 'ergonomic', 'chair', 'comfort'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'prod4',
    title: 'Fitness Tracker Watch - Health & Sports Monitor',
    description: 'Track your fitness goals with our advanced smartwatch featuring heart rate monitoring, GPS, and 7-day battery life.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=500&h=500&fit=crop',
    ],
    category: 'sports',
    subcategory: 'fitness',
    brand: 'FitLife',
    seller: mockSellers[2],
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery Life': '7 days',
      'Water Resistance': '50m',
      'Sensors': 'Heart Rate, GPS, Accelerometer',
      'Compatibility': 'iOS & Android',
    },
    features: [
      '24/7 Heart Rate Monitoring',
      'Built-in GPS',
      'Sleep Tracking',
      '100+ Sport Modes',
      'Smartphone Notifications',
    ],
    inStock: true,
    stockQuantity: 67,
    rating: 4.5,
    reviewCount: 432,
    reviews: [],
    variants: [
      {
        id: 'size',
        name: 'Size',
        options: [
          { value: '40mm', inStock: true },
          { value: '44mm', inStock: true },
        ],
      },
      {
        id: 'color',
        name: 'Band Color',
        options: [
          { value: 'Black', inStock: true },
          { value: 'Blue', inStock: true },
          { value: 'Pink', inStock: true },
        ],
      },
    ],
    tags: ['fitness', 'smartwatch', 'health', 'gps'],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-05-22'),
  },
  {
    id: 'prod5',
    title: 'Premium Coffee Maker - 12-Cup Programmable',
    description: 'Brew the perfect cup every time with our premium coffee maker featuring programmable settings and thermal carafe.',
    price: 129.99,
    originalPrice: 179.99,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1517216085-4241ce9d18a6?w=500&h=500&fit=crop',
    ],
    category: 'home-garden',
    subcategory: 'kitchen',
    brand: 'BrewMaster',
    seller: mockSellers[1],
    specifications: {
      'Capacity': '12 cups',
      'Carafe': 'Thermal Stainless Steel',
      'Programming': '24-hour delay brew',
      'Dimensions': '14" x 10" x 16"',
      'Warranty': '2 years',
    },
    features: [
      'Programmable Timer',
      'Auto Shut-off',
      'Brew Strength Control',
      'Water Filter',
      'Easy Clean Function',
    ],
    inStock: true,
    stockQuantity: 28,
    rating: 4.4,
    reviewCount: 298,
    reviews: [],
    tags: ['coffee', 'kitchen', 'programmable', 'thermal'],
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-05-19'),
  },
  {
    id: 'prod6',
    title: 'Gaming Mechanical Keyboard - RGB Backlit',
    description: 'Enhance your gaming experience with our mechanical keyboard featuring customizable RGB lighting and tactile switches.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&h=500&fit=crop',
    ],
    category: 'electronics',
    subcategory: 'gaming',
    brand: 'GameTech',
    seller: mockSellers[0],
    specifications: {
      'Switch Type': 'Blue Mechanical',
      'Backlighting': 'RGB with 16.8M colors',
      'Layout': 'Full-size (104 keys)',
      'Connection': 'USB-C',
      'Polling Rate': '1000Hz',
    },
    features: [
      'Customizable RGB Lighting',
      'Anti-Ghosting',
      'Dedicated Media Keys',
      'USB Passthrough',
      'Gaming Mode',
    ],
    inStock: true,
    stockQuantity: 52,
    rating: 4.6,
    reviewCount: 167,
    reviews: [],
    variants: [
      {
        id: 'switches',
        name: 'Switch Type',
        options: [
          { value: 'Blue (Clicky)', inStock: true },
          { value: 'Red (Linear)', inStock: true },
          { value: 'Brown (Tactile)', inStock: false },
        ],
      },
    ],
    tags: ['gaming', 'mechanical', 'rgb', 'keyboard'],
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-05-25'),
  },
];

// Mock User
export const mockUser: User = {
  id: 'user1',
  email: 'john.doe@example.com',
  firstName: 'John',
  lastName: 'Doe',
  phone: '+1 (555) 123-4567',
  addresses: [
    {
      id: 'addr1',
      type: 'home',
      firstName: 'John',
      lastName: 'Doe',
      address1: '123 Main Street',
      address2: 'Apt 4B',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'United States',
      phone: '+1 (555) 123-4567',
      isDefault: true,
    },
  ],
  paymentMethods: [
    {
      id: 'pm1',
      type: 'credit',
      last4: '4242',
      brand: 'Visa',
      expiryMonth: 12,
      expiryYear: 2027,
      isDefault: true,
    },
  ],
  orders: [],
  wishlist: ['prod2', 'prod4'],
  createdAt: new Date('2023-06-15'),
};

// Featured deals and recommendations
export const featuredDeals = mockProducts.filter(p => p.originalPrice);
export const topRatedProducts = mockProducts.filter(p => p.rating >= 4.5);
export const newArrivals = mockProducts.slice(-3);
